name: Rebuild dist

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  rebuild-dist:
    name: Rebuild dist
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # https://github.com/actions/checkout/blob/v7.0.1/README.md#push-a-commit-to-a-pr-using-the-built-in-token
      - uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          package-manager-cache: false
      - name: Install pnpm
        run: >
          npm install --global corepack@latest &&
          corepack enable &&
          corepack prepare pnpm@latest-11 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      # Created commit through the GitHub API, which signs it.
      - name: Stage dist
        run: git add --all dist/
      - name: Commit dist if changed
        uses: grafana/github-api-commit-action@b1d81091e8480dd11fcea8bc1f0ab977a0376ca5 # v1.0.0
        with:
          commit-message: Rebuild dist
          success-if-no-changes: true
          token: ${{ github.token }}
